-- Concierge CSV import for daily_report_history (run in Lovable SQL editor)
-- Rows: 7 (deduplicated from 20 CSV rows)

INSERT INTO public.daily_report_history ("report_date", "shift_type", "staff_user_id", "staff_name", "future_shift_notes", "member_feedback", "membership_requests", "facility_issues", "busiest_areas", "system_issues", "management_notes", "status", "created_at", "updated_at", "tour_followup_completed")
  VALUES
  ('2026-01-25', 'AM', '79b569b8-2e63-484c-bb2e-4ec1f4712c47', 'Hunter Johnson', '[{"text":"Ms. Boxrud paid for Joseph Rubin''s week pass. His wife, Jessica Powell might also come in today, if so she needs to be charged the 1 week membership but do it on Sinder Boxrud''s account and select the ''paying for'' option in top right corner. :)"}]'::jsonb, '[{"sentiment":"negative","text":"Tori Taylor would like to speak with a manager about the glitch waiver before signing it, therefore preventing her from using app to sign up for classes"}]'::jsonb, '[]'::jsonb, '[{"text":"Cable Machine weight doesn''t go all the way down - the pin is at the front desk\nOne of the normatec boots pops open- Put in the Old Closet in the cabinet where the out of order signs are"}]'::jsonb, '-Main Gym 8:30am
-Cardio 10:45am
-Main Gym 11am
-Rooftop 11:15am
-Men''s spa 12pm
-Cardio 12:15pm', '[]'::jsonb, '-Raisa was wondering if theres a way to get text alert notifications from when a client schedules the session? She said when she schedules the session theres a text but not when the client books themselves. It happens when members book sessions less than a 24hour notice
- Tori Taylor would like to speak with a manager about the glitch waiver before signing it, therefore preventing her from using app to sign up for classes', 'submitted', '2026-01-25T20:40:43.740Z', '2026-01-25T20:40:43.740Z', true),
  ('2026-02-01', 'AM', '4aa6ccce-23a8-4e37-863c-5b5bcbba1e14', 'Lydia Engel', '[{"text":"Brook Sill has a guest coming in today from Hawaii, but she''s unable to meet her at HUME, if you could, please orient them through the space when they come in this afternoon"}]'::jsonb, '[{"sentiment":"negative","text":"Britt Johnson Sent an emailing asking about some sort of reimbursement because our recent renovations were extended and interfered with her regular use of the facility."}]'::jsonb, '[{"text":"[PAUSE] Emily Woodall <emilywoodalldesign@gmail.com> - Not in the thread [NON-PAID] (Pause Start: 02/07/2026)"}]'::jsonb, '[{"text":"N/A"}]'::jsonb, '-Main Gym 9:30am-11am, 12:30 pm
-Cafe 10:15am
-Impact Room 10am

Cafe she really really busy throughout the shift', '[]'::jsonb, '-Kaitlin Freedman Had to reschedule her massage for the 3rd time due to Arketa overlapping this time with massages. She was a little upset and Alex came down was wondering how someone booked a massage with chase that lasted till the middle of her clients appointment?. I offered Kaitlin a discount on the massage or a complimentary service due to things needing to be reschedule again she said she''ll let us know.

-Ian said she was really rude in his class to him and just wasn''t following directions.', 'submitted', '2026-02-01T21:21:01.523Z', '2026-02-02T01:49:38.127Z', true),
  ('2026-01-17', 'PM', 'e8766151-cd80-4fe0-a22b-4b105128e0e2', 'Grace Cotton', '[]'::jsonb, '[{"sentiment":"neutral","text":"Jennifer Miller - has lost a shoe!"}]'::jsonb, '[]'::jsonb, '[]'::jsonb, 'Super chill day - not a whole lot going on.', '[]'::jsonb, 'Joseph August came and stopped by the front desk - he toured with Dylan in November. Has super great energy and think he should be in the gym ASAP! I did mention we are at capacity but that I would escalate his situation to management. Crossing my fingers and toes for him!', 'submitted', '2026-01-18T03:00:23.824Z', '2026-01-18T03:00:23.824Z', true),
  ('2026-02-14', 'PM', 'e8766151-cd80-4fe0-a22b-4b105128e0e2', 'Grace Cotton', '[]'::jsonb, '[{"sentiment":"positive","text":"People loved the flower arrangement''s."}]'::jsonb, '[]'::jsonb, '[{"text":"Locker 63 in mens broken"}]'::jsonb, 'Literalleh nothing happened today.', '[]'::jsonb, 'Skevo Zembillas needs to update his payment method. Tried to run his card through Arketa for monthly payment but it didn''t go through. Felt awkward to tell him it wasn''t going through.

Also Elijah told me that he did the roof but something about him not being able to take the photo? Confused.', 'submitted', '2026-02-15T02:50:25.334Z', '2026-02-15T02:50:25.334Z', true),
  ('2026-02-01', 'PM', '79b569b8-2e63-484c-bb2e-4ec1f4712c47', 'Hunter Johnson', '[]'::jsonb, '[]'::jsonb, '[{"text":"[CANCEL] Bianca Emde  - Not coming enough (End Date: 02/07/2026)"}]'::jsonb, '[{"text":"The part to adjust this is missing"}]'::jsonb, 'Pretty mellow, busy for classes', '[]'::jsonb, NULL, 'submitted', '2026-02-02T03:09:23.205Z', '2026-02-02T03:09:23.205Z', true),
  ('2026-02-08', 'PM', '4aa6ccce-23a8-4e37-863c-5b5bcbba1e14', 'Lydia Engel', '[{"text":"Osea bag for Ben in cabinet behind front desk"}]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[{"text":"The compression suit table is super close to hbot. Can someone please move it over pls? \nThere''s are a bunch of random boxes and stuff around the hbot. Sandy wants it to look presentable there but we don''t know where all that stuff goes"}]'::jsonb, 'Recovery lounge busy at 3', '[]'::jsonb, NULL, 'submitted', '2026-02-09T02:53:43.902Z', '2026-02-09T02:53:43.902Z', true),
  ('2026-01-24', 'PM', '4aa6ccce-23a8-4e37-863c-5b5bcbba1e14', 'Lydia Engel', '[{"text":"Nope"}]'::jsonb, '[{"sentiment":"positive","text":"No"}]'::jsonb, '[]'::jsonb, '[{"text":"just a few equipment pieces Richard is fixing"}]'::jsonb, '9am cardio 
Means sp 9:30am
10am-12pm Main Gym
Cafe 11am', '[]'::jsonb, 'Nope', 'submitted', '2026-01-24T21:06:21.290Z', '2026-01-24T21:06:21.290Z', true)
  ON CONFLICT (report_date, shift_type) DO UPDATE SET "staff_user_id" = EXCLUDED."staff_user_id", "staff_name" = EXCLUDED."staff_name", "future_shift_notes" = EXCLUDED."future_shift_notes", "member_feedback" = EXCLUDED."member_feedback", "membership_requests" = EXCLUDED."membership_requests", "facility_issues" = EXCLUDED."facility_issues", "busiest_areas" = EXCLUDED."busiest_areas", "system_issues" = EXCLUDED."system_issues", "management_notes" = EXCLUDED."management_notes", "status" = EXCLUDED."status", "created_at" = EXCLUDED."created_at", "updated_at" = EXCLUDED."updated_at", "tour_followup_completed" = EXCLUDED."tour_followup_completed";

