
-- Add missing columns to arketa_reservations_staging
ALTER TABLE public.arketa_reservations_staging
  ADD COLUMN IF NOT EXISTS booking_id TEXT,
  ADD COLUMN IF NOT EXISTS email_marketing_opt_in BOOLEAN,
  ADD COLUMN IF NOT EXISTS date_purchased TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS instructor_name TEXT,
  ADD COLUMN IF NOT EXISTS location_name TEXT,
  ADD COLUMN IF NOT EXISTS location_address TEXT,
  ADD COLUMN IF NOT EXISTS purchase_type TEXT,
  ADD COLUMN IF NOT EXISTS estimated_gross_revenue NUMERIC,
  ADD COLUMN IF NOT EXISTS estimated_net_revenue NUMERIC,
  ADD COLUMN IF NOT EXISTS coupon_code TEXT,
  ADD COLUMN IF NOT EXISTS package_name TEXT,
  ADD COLUMN IF NOT EXISTS package_period_start TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS package_period_end TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS offering_id TEXT,
  ADD COLUMN IF NOT EXISTS payment_method TEXT,
  ADD COLUMN IF NOT EXISTS payment_id TEXT,
  ADD COLUMN IF NOT EXISTS service_id TEXT,
  ADD COLUMN IF NOT EXISTS tags JSONB,
  ADD COLUMN IF NOT EXISTS canceled_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS canceled_by TEXT,
  ADD COLUMN IF NOT EXISTS milestone INTEGER;

-- Add missing columns to arketa_reservations_history (needs all 21 + experience_type + purchase_id)
ALTER TABLE public.arketa_reservations_history
  ADD COLUMN IF NOT EXISTS booking_id TEXT,
  ADD COLUMN IF NOT EXISTS email_marketing_opt_in BOOLEAN,
  ADD COLUMN IF NOT EXISTS date_purchased TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS instructor_name TEXT,
  ADD COLUMN IF NOT EXISTS location_name TEXT,
  ADD COLUMN IF NOT EXISTS location_address TEXT,
  ADD COLUMN IF NOT EXISTS purchase_type TEXT,
  ADD COLUMN IF NOT EXISTS estimated_gross_revenue NUMERIC,
  ADD COLUMN IF NOT EXISTS estimated_net_revenue NUMERIC,
  ADD COLUMN IF NOT EXISTS coupon_code TEXT,
  ADD COLUMN IF NOT EXISTS package_name TEXT,
  ADD COLUMN IF NOT EXISTS package_period_start TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS package_period_end TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS offering_id TEXT,
  ADD COLUMN IF NOT EXISTS payment_method TEXT,
  ADD COLUMN IF NOT EXISTS payment_id TEXT,
  ADD COLUMN IF NOT EXISTS service_id TEXT,
  ADD COLUMN IF NOT EXISTS tags JSONB,
  ADD COLUMN IF NOT EXISTS experience_type TEXT,
  ADD COLUMN IF NOT EXISTS purchase_id TEXT,
  ADD COLUMN IF NOT EXISTS canceled_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS canceled_by TEXT,
  ADD COLUMN IF NOT EXISTS milestone INTEGER;
