-- Migration: 20260130165252_seed_historical_weekly_updates.sql
-- Seed historical weekly updates

INSERT INTO public.staff_announcements (
  id, title, content, announcement_type, priority, target_departments,
  week_start_date, photo_url, expires_at, scheduled_at, is_active,
  created_by, created_by_id, created_at
) VALUES
('cf640abb-f12f-4b93-8263-05f0d6d003f4', 'Weekly Updates - 12/5/25',
E'SAUNA & STEAM ROOM:\nThere is a new change to the sauna and steam room policy–the steam room is going to be programmed 15 minutes before close instead of 30 mins. Members are now allowed to stay in both spaces until 15 minutes before close.\n\nVENN DIAGRAM FOR CC''S:\nThere is a new chart for who to CC/ forward emails to. It can be found in the master email templates. Please check before forwarding because many more things are being sent to Abbey and Roger than needed. Please use the events form template when anyone inquires about a photoshoot/ space rental/ event.\n\nNEW PAYMENT TERMINAL:\nWe now have a tap to pay option! The tap to pay terminal will live at the front desk. For members, proceed as usual and then select "send to payment terminal" → select Payment Terminal → send to payment terminal again and then tap to pay. You can email receipts the same way you normally do.\n\nFor non members, click the "New Sale" button that lives above the "Home" button in the top left corner of arketa. Once selected, click "create a walk in sale" under "search client". The terminal will need to stay charged, so please keep an eye on it.\n\nNEW MEMBER & GUEST POLICY CARDS:\nThese need to be given out every time there is a guest and every time there is a new member. There are backups in the cabinet behind the desk.\n\nNEW MAT CLEANING LOCATION:\nThe office is officially gone. The new mat cleaning spot is now in the garage next to where the break room will be (far left corner of the garage, past the huge towel bins).\n\nNEW DATABASE:\nI have created a new database! This is a way to consolidate the many forms we have into one spot. This will now be filled out instead of the daily reports apply, will let them know when a spot opens up.',
'weekly_update', 'normal', NULL, '2025-12-01', NULL, NULL, NULL, true, 'Management', NULL, '2025-12-12 00:28:38.865527+00'),

('d12e6cc0-eb36-4055-b7c3-b008405b2a06', 'Weekly Updates - 12/2/25',
E'NEW TEMPLATES:\nThere are new templates for the following:\n1. If a brand or someone in the industry wants to come see the space (it is a polite no)\n2. If people complain about the pause policy/ billing cycle\n3. For questions/ complaints regarding the upcoming holiday/ renovation closure\n\nAll can be found in the master email templates doc. For context: we currently have many people on our waitlist, which means we are able to enforce our policies and risk the cancellations. We will not be offering exemptions 99% of the time.\n\nAPPOINTMENT AVAILABILITY LINK:\nYou can send links to view appointment availability. This will be helpful if someone is like "I want to book a massage next week. When is available?". I added the links to the important links page.\n\nTEMPORARY PASSES REMINDER:\nReminder on day passes and temporary passes: you can still send an application for temporary passes or day passes when people inquire. However, please know that our day passes/ temp memberships now require member referral and a week''s notice. Since we are at capacity, Roger is approving all temporary passes.\n\nPAUSE/ CANCELLATION IN DAILY NOTES:\nPlease do not add just a name under the "pause/ cancellation" section. Add full name, whether they are pausing or canceling, and the reason.\n\nCAPACITY & NEW MEMBERS:\nWhen I say we are "at capacity", this means we are not increasing the number of members that we have. However, we are still accepting new members when spots become available.',
'weekly_update', 'normal', NULL, '2025-12-01', NULL, NULL, NULL, true, 'Management', NULL, '2025-12-12 00:28:38.865527+00'),

('b752fcd2-d469-4d3c-8bdc-1be9b595e165', 'Weekly Updates - 11/21/25',
E'SWAPPING CLASSES:\nThe members are trying to get sneaky by asking us to swap them out of one class and into another to avoid the late cancel fees.\n\nSwapping Class - 1st Time Request:\nThank you for reaching out! We are able to facilitate the switch as a one-time courtesy. In the future, to switch classes, please first cancel the class you are currently signed up for through the app.\n\nSwapping Class - Repeated Request:\nThank you for reaching out! To switch classes, please cancel the class you are currently signed up for through the app.\n\nNEW STUDIO:\nThe new HIIT studio will have 8 treadmills and boxing bags. Please don''t mention classes or other programming in there to members yet.\n\nDAILY NOTES - CANCELLATIONS/ PAUSES:\nPlease don''t just put someone''s name in the "cancellation/ pause" section with no additional information. Please add if they paused or cancelled with the reason why.\n\nCANCELLING AN APPLICATION:\nIf someone wants to cancel their application and they have already given CC, you must cancel their "trial membership".\n\nEARLY CLOSURE:\nWe will be closed for thanksgiving next Thursday and we close early on Wednesday at 1:30 PM.\n\nARKETA INBOX:\nThe arketa inbox has been a little neglected. Please be sure to close out a conversation once it has been answered.\n\nDAY PASSES/ SERVICES AVAILABLE TO NON MEMBERS:\nWe are no longer selling day passes or temporary memberships to randoms. To purchase a day pass, use a service, or get a temp membership, the person must fill out the temp pass application at least one week before their intended visit with a member referral.',
'weekly_update', 'normal', NULL, '2025-11-17', NULL, NULL, NULL, true, 'Management', NULL, '2025-12-12 00:28:38.865527+00'),

('65d67a4c-074c-4e80-a9fe-dbf8182791f9', 'Weekly Updates - 11/14/25',
E'CAPACITY:\nWe are aware capacity is an issue and have capped membership. If someone complains, please ask them what space was full, what time, etc.\n\nGOODBYE BELLA:\nOur beautiful Bella has moved on from HUME. Dustin is now our Events and Partnerships Lead. Abbey will be continuing her social media/ content role at a greater capacity.\n\nCONCERNS/ QUESTIONS TRACKER:\nRemember to please add your questions/ concerns in the tracker instead of just in notes!\n\nTARP FOLDING:\nPlease fold tarps after uncovering the machines in the morning and drape them over the railings.\n\nCLOCKING OUT:\nDo not clock in before you are in the facilities. Clock out when you leave the facilities.\n\nBREAKS:\nWeekday AM - clock out for break by 10:20 at the LATEST\nWeekday PM - clock out for break by 6:20 at the LATEST\nWeekend AM - clock out for break by 11:20 at the LATEST\nWeekend PM - 5:50 at the LATEST\n\nLOST AND FOUND:\nIt is in the old staff closet. Please do not let that closet get messy.\n\nOSEA LAUNCH:\nWe are now selling OSEA retail! All products are in arketa. There is an OSEA product reference page on our important links.',
'weekly_update', 'normal', NULL, '2025-11-10', NULL, NULL, NULL, true, 'Management', NULL, '2025-12-12 00:28:38.865527+00'),

('32dd183b-4742-466b-ada4-be8185672df5', 'Weekly Updates - 10/24/25',
E'PRICING REMINDER:\nThe new membership price is $450, not $495. The new annual rate is $4,595 (no initiation).\n\nPOLICY CARDS:\nReminder to please give out policy cards to guests, day pass holders, and new members!\n\nMASTERCARD:\nIf someone reaches out inquiring about Mastercard, please give them my email and let them know I am happy to help.\n\nPOTENTIAL MEMBERS ASKING FOR OLD PRICING:\nUnless someone has already put in CC info for Phase 2 pricing, they cannot get Phase 2 pricing. There is 0.1% room for negotiation.\n\nHBOT BEING LEFT ON:\nThe HBOT keeps being left on. Even if the member prefers to let themselves out, please remember to turn the HBOT off afterward and remake the sheets.\n\nNEW MASTER EMAIL GUIDE & OUTLOOK FOLDER:\nDustin has put together a new Master Email Templates guide! It is beautiful and should be fully up to date.\n\nPAUSE CHART:\nRoger still wants us to track all pause requests. Please remember to update it!\n\nCANCELLATIONS:\nReminder to always get a reason before confirming a cancellation!\n\nTRAINER/ INSTRUCTOR AVAIL:\nThere is now a document that has the general availability of our instructors and trainers on the important links page.',
'weekly_update', 'normal', NULL, '2025-10-20', NULL, NULL, NULL, true, 'Management', NULL, '2025-12-12 00:28:38.865527+00'),

('1b3edfaf-6d9d-4550-a294-a9b41fd3a54b', 'WEEKLY UPDATES 12-12-25',
E'GOODBYE JOLT:\nWe have a new app! It is built by me and we will be trialing it out over the next several weeks.',
'weekly_update', 'normal', NULL, '2025-12-12', NULL, NULL, NULL, true, 'Jillian Brenner', NULL, '2025-12-12 21:17:00.143917+00'),

('a69fe6f7-7b79-4015-a0c1-601f5c821f1b', '1/16/26',
E'DATABASE LINK:\nI will now be referring to the database as the "OS", short for Operations System.',
'weekly_update', 'normal', ARRAY['concierge'], '2026-01-16', NULL, NULL, NULL, true, 'Management', NULL, '2026-01-16 19:54:35.826607+00')
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  content = EXCLUDED.content,
  announcement_type = EXCLUDED.announcement_type,
  priority = EXCLUDED.priority,
  target_departments = EXCLUDED.target_departments,
  week_start_date = EXCLUDED.week_start_date,
  is_active = EXCLUDED.is_active,
  created_by = EXCLUDED.created_by,
  created_at = EXCLUDED.created_at;