-- Create direct upsert function that bypasses PostgREST entirely
-- This function runs entirely in PostgreSQL, no PostgREST layer involved

CREATE OR REPLACE FUNCTION public.direct_upsert_reservation(
  p_external_id text,
  p_booking_id text,
  p_client_id text,
  p_client_email text,
  p_first_name text,
  p_last_name text,
  p_class_name text,
  p_class_time timestamptz,
  p_status text,
  p_location_name text,
  p_data jsonb DEFAULT '{}'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.arketa_reservations (
    external_id,
    booking_id,
    client_id,
    client_email,
    first_name,
    last_name,
    class_name,
    class_time,
    status,
    location_name,
    -- Additional fields from jsonb
    email_marketing_opt_in,
    date_purchased,
    purchase_id,
    reservation_type,
    class_id,
    instructor_name,
    location_address,
    checked_in,
    checked_in_at,
    purchase_type,
    gross_amount_paid,
    net_amount_paid,
    estimated_gross_revenue,
    estimated_net_revenue,
    coupon_code,
    package_name,
    package_period_start,
    package_period_end,
    offering_id,
    payment_method,
    payment_id,
    service_id,
    tags,
    experience_type,
    late_cancel,
    canceled_at,
    canceled_by,
    milestone
  )
  VALUES (
    p_external_id,
    p_booking_id,
    p_client_id,
    p_client_email,
    p_first_name,
    p_last_name,
    p_class_name,
    p_class_time,
    p_status,
    p_location_name,
    -- Extract from jsonb
    (p_data->>'email_marketing_opt_in')::text,
    (p_data->>'date_purchased')::timestamptz,
    (p_data->>'purchase_id')::text,
    (p_data->>'reservation_type')::text,
    (p_data->>'class_id')::text,
    (p_data->>'instructor_name')::text,
    (p_data->>'location_address')::text,
    (p_data->>'checked_in')::boolean,
    (p_data->>'checked_in_at')::timestamptz,
    (p_data->>'purchase_type')::text,
    (p_data->>'gross_amount_paid')::decimal,
    (p_data->>'net_amount_paid')::decimal,
    (p_data->>'estimated_gross_revenue')::decimal,
    (p_data->>'estimated_net_revenue')::decimal,
    (p_data->>'coupon_code')::text,
    (p_data->>'package_name')::text,
    (p_data->>'package_period_start')::timestamptz,
    (p_data->>'package_period_end')::timestamptz,
    (p_data->>'offering_id')::text,
    (p_data->>'payment_method')::text,
    (p_data->>'payment_id')::text,
    (p_data->>'service_id')::text,
    (p_data->'tags')::jsonb,
    (p_data->>'experience_type')::text,
    (p_data->>'late_cancel')::boolean,
    (p_data->>'canceled_at')::timestamptz,
    (p_data->>'canceled_by')::text,
    (p_data->>'milestone')::integer
  )
  ON CONFLICT (external_id) DO UPDATE SET
    booking_id = EXCLUDED.booking_id,
    client_id = EXCLUDED.client_id,
    client_email = EXCLUDED.client_email,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    class_name = EXCLUDED.class_name,
    class_time = EXCLUDED.class_time,
    status = EXCLUDED.status,
    location_name = EXCLUDED.location_name,
    email_marketing_opt_in = EXCLUDED.email_marketing_opt_in,
    date_purchased = EXCLUDED.date_purchased,
    purchase_id = EXCLUDED.purchase_id,
    reservation_type = EXCLUDED.reservation_type,
    class_id = EXCLUDED.class_id,
    instructor_name = EXCLUDED.instructor_name,
    location_address = EXCLUDED.location_address,
    checked_in = EXCLUDED.checked_in,
    checked_in_at = EXCLUDED.checked_in_at,
    purchase_type = EXCLUDED.purchase_type,
    gross_amount_paid = EXCLUDED.gross_amount_paid,
    net_amount_paid = EXCLUDED.net_amount_paid,
    estimated_gross_revenue = EXCLUDED.estimated_gross_revenue,
    estimated_net_revenue = EXCLUDED.estimated_net_revenue,
    coupon_code = EXCLUDED.coupon_code,
    package_name = EXCLUDED.package_name,
    package_period_start = EXCLUDED.package_period_start,
    package_period_end = EXCLUDED.package_period_end,
    offering_id = EXCLUDED.offering_id,
    payment_method = EXCLUDED.payment_method,
    payment_id = EXCLUDED.payment_id,
    service_id = EXCLUDED.service_id,
    tags = EXCLUDED.tags,
    experience_type = EXCLUDED.experience_type,
    late_cancel = EXCLUDED.late_cancel,
    canceled_at = EXCLUDED.canceled_at,
    canceled_by = EXCLUDED.canceled_by,
    milestone = EXCLUDED.milestone,
    updated_at = NOW();
END;
$function$;

GRANT EXECUTE ON FUNCTION public.direct_upsert_reservation TO service_role, authenticated;

COMMENT ON FUNCTION public.direct_upsert_reservation IS 'Direct database upsert bypassing PostgREST - workaround for cache issues';
